import React, { useState } from 'react'
import Head from 'next/head'
import Box from '@mui/material/Box';
import Card from '@mui/material/Card';
import CardActions from '@mui/material/CardActions';
import CardContent from '@mui/material/CardContent';
import Button from '@mui/material/Button';
import Typography from '@mui/material/Typography';
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { styled } from '@mui/material/styles';
import Paper from '@mui/material/Paper';
import Grid from '@mui/material/Grid';
import TextField from '@mui/material/TextField';
import Stack from '@mui/material/Stack';
import {authapi} from '../pages/service/auth';
import Link from 'next/link';


const inter = Inter({ subsets: ['latin'] })


export default function signup() {
    const [username,setUsername] = useState("");
    const [email,setEmail] = useState("");
    const [password,setPassword] = useState("");
    const [error,setError] = useState("");
    const onInputChange = (e) => {
        if(e.target.name=="username")
        {
            console.log(e.target.value);
            setUsername(e.target.value);
        }
        if(e.target.name=="email")
        {
            setEmail(e.target.value);
        }
        if(e.target.name=="password")
        {
            setPassword(e.target.value);
        }
    }
    const onInputSubmit=async (e)=>{
        const data={username ,email ,password};
        if(username==''){
            setError("Enter Your Usename!");
        }
        else if(email==''){
            setError("Enter Your Email!");
        }
        else if(password==''){
            setError("Create Your Password!");
        }
        else
        {
            setError("");
            // console.log("success :"+name +" "+email+" "+phone+" "+password);
            const response = await authapi.addUser(data);
            // console.log(response.data);
            if (response.status === 200 ) {
                setError("Successfully Registered!");
                setUsername("");
                setEmail("");
                setPassword("");
            }
            else
            {
                setError("Something went wrong!");
            }
        }
    }
    return (<>
        <Head>
            <title>Sign Up</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={`${styles.main} ${inter.className}`}>
            <Box sx={{ flexGrow: 1 }}>
                <Grid container direction="row" justifyContent="center"  alignItems="center" spacing={2}>
                    <Grid item xs={3}>
                        <Card sx={{ minWidth: 275 }}>
                            <CardContent>
                                <Typography sx={{ fontSize: 14 }} color="text.primary" gutterBottom>
                                    Sign Up
                                </Typography>
                                <Typography style={{ color: "red" }}>{error}</Typography>
                                <Box sx={{ flexGrow: 1 }}>
                                    <Grid container direction="row" justifyContent="center"  alignItems="center" spacing={0}>
                                        <Grid item xs={12}>
                                            <TextField  name="username" onChange={onInputChange} label="Username" value={username} variant="standard" />
                                        </Grid>
                                        <Grid item xs={12}>
                                            <TextField  name="email" onChange={onInputChange} label="Email" value={email} variant="standard" />
                                        </Grid>
                                        <Grid item xs={12}>
                                            <TextField  name="password" onChange={onInputChange}  label="Create Password" value={password} variant="standard" />
                                        </Grid>
                                    </Grid>
                                </Box>
                            </CardContent>
                            <CardActions>
                                <Stack spacing={2} direction="row">
                                         <Button variant="contained" onClick={onInputSubmit}>Submit</Button>
                                </Stack>
                            </CardActions>
                            <Typography>Already a member? <Link href="/signin">SignIn</Link></Typography>
                        </Card>
                    </Grid>
                </Grid>
            </Box>
        </main>
    </>
    )
}
